apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb-service
  namespace: prometheus
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - port: 80        # External port
      targetPort: 9090 # Prometheus container port
