apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: react-application
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
